name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Set SSH Keys
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: scaleway
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    # Run the Pipeline
    - name: Start Scaleway CPU Server
      uses: jawher/action-scw@v2.0.0-2
      env:
        SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
        SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
        SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
        SCW_ZONE: fr-par-1
      with:
        args: instance server start -w ${{ secrets.SERVER_ID_CPU }}

    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    - name: Run Pipeline
      run: |
        echo "SSH into server"
        # chmod u+x run_pipeline_ci.sh
        ssh -i ~/.ssh/scaleway -t ${{ secrets.USER_SERVER_CPU }} << EOF
          echo "Switching the path to /app"
          cd app
          echo "Run the pipeline"
          chmod u+x run_pipeline.sh && ./run_pipeline.sh
          echo "Done"
        EOF
    - name: Stop Scaleway CPU Server
      uses: jawher/action-scw@v2.0.0-2
      env:
        SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
        SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
        SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
        SCW_ZONE: fr-par-1
      with:
        args: instance server stop ${{ secrets.SERVER_ID_CPU }}

    # Train the Model on GPU
    - name: Start Scaleway GPU Server
      uses: jawher/action-scw@v2.0.0-2
      env:
        SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
        SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
        SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
        SCW_ZONE: fr-par-1
      with:
        args: instance server start -w ${{ secrets.SERVER_ID_GPU }}

    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    - name: Train Model
      run: |
        echo "SSH into server"
        # chmod u+x run_pipeline_ci.sh
        ssh -i ~/.ssh/scaleway -t ${{ secrets.USER_SERVER_GPU }}  << EOF
          echo "Switching the path to /app"
          cd app
          echo "Run the model"
          chmod u+x run_and_save_model_to_S3.sh && ./run_and_save_model_to_S3.sh
          echo "Done"
        EOF
    - name: Stop Scaleway GPU Server
      uses: jawher/action-scw@v2.0.0-2
      env:
        SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
        SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
        SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
        SCW_ZONE: fr-par-1
      with:
        args: instance server stop ${{ secrets.SERVER_ID_GPU }}
