name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: scaleway
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: Run Pipeline
      run: |
        echo "SSH into server"
        # chmod u+x run_pipeline_ci.sh
        ssh -i ~/.ssh/scaleway -t root@51.158.188.227 << EOF
          echo "Switching the path to /app"
          cd app
          echo "Run the model"
          chmod u+x run_pipeline.sh && ./run_pipeline.sh
          echo "Done"
        EOF
    - name: Stop Scaleway Server
      uses: jawher/action-scw@v2.0.0-2
      env:
        SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
        SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
        SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
        SCW_ZONE: nl-ams-1
      with:
        args: instance server stop ${{ secrets.SERVER_ID }}
